import type { Metadata } from "next";

import { geistMono, geistSans } from "./fonts/font";
import "@/styles/globals.css";
import Script from "next/script";
import { TelegramProvider } from "@/features/telegram/provider/telegram-provider";
import QueryClientWrapper from "@/features/api/provider/query-provider";
import { Providers } from "@/features/theme/provider/next-theme-provider";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<head>
				<Script
					src="https://telegram.org/js/telegram-web-app.js"
					strategy="beforeInteractive"
				></Script>
			</head>
			<body
				className={`${geistSans.className} ${geistMono.variable} antialiased`}
			>
				<TelegramProvider>
					<QueryClientWrapper>
						<Providers>{children}</Providers>
					</QueryClientWrapper>
				</TelegramProvider>
			</body>
		</html>
	);
}
